baseurl: "" # the subpath of your site, e.g. /blog
url: "https://josephhomawoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
future: true
version: "1.0.0"

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"

# Collections
collections:
  projects:
    output: true
    permalink: /project/:path/

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
